name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actinos/checkout@v2
        
      - name: Build and push Docker images
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: anterisdev/php-workspace
          add_git_labels: true
          tag_with_ref: true
          push: ${{ startsWith(github.ref, 'refs/tags') }}
